import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import NavbarC from "@/components/nav-bar";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tarif Dünyası",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="tr">
        <Toaster />
        <body className={inter.className}>
          <NextUIProvider>
            <NavbarC />
            {children}
          </NextUIProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
